[save]
format_on_save = true
autosave = "after_delay"
autosave_delay = 1000

[experimental]

[runtime]
watcher_on_save = "lazy"
default_sql_output = "auto"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
reactive_tests = true
auto_reload = "autorun"
output_max_bytes = 8000000
auto_instantiate = false
default_auto_download = []

[mcp]
presets = []

[mcp.mcpServers]

[display]
default_width = "medium"
cell_output = "below"
code_editor_font_size = 14
theme = "light"
dataframes = "rich"
default_table_page_size = 10
default_table_max_columns = 50
reference_highlighting = false

[language_servers.pylsp]
enable_pydocstyle = false
enable_mypy = true
enable_pyflakes = false
enable_ruff = true
enable_flake8 = false
enabled = false
enable_pylint = false

[language_servers.ty]
enabled = false

[language_servers.basedpyright]

[formatting]
line_length = 79

[server]
browser = "default"
follow_symlink = false

[snippets]
custom_paths = []
include_default_snippets = true

[datasources]

[completion]
copilot = false
activate_on_typing = true

[diagnostics]
enabled = false
sql_linter = true

[ai]
mode = "manual"
inline_tooltip = false
rules = ""

[ai.models]
displayed_models = []
custom_models = []

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[package_management]
manager = "uv"
