# Don't put credentials or other secrets into this shared file!
[env]
dotenv = ".env"   # auto-load .env file
# editorconfig-checker-disable-next-line
CHECK_UUID = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRnIrc2E0cU1zV2dqMm0zdllpTkZlcTJidE5lbzBWZy8yRitwS1VTVERBCk1NbVNESkhURVh2VDh0WHNGakJHSmpXQVBRRE5YbG9kOGdEU2VVWVVNcEEKLT4gc35SO08tZ3JlYXNlIHUrIUIgZgpQR2YxYkFyN0xqUnRodDl2dDRheldUeE9sOFVVCi0tLSBvT01aZWhXUXJ5T21JemZ3TUx3WVQ5d0RpMG9Uc3Q0dXZvNHFBVGhDOVhrCi6oIuA390VzkPHv5FAN3wx6KdWx3ty+btbi8RM+JtODrX4pINYuyBqM9/aMYf577uJ9g88QUTlqO4dVF1PfCgxKSCG6" }
# editorconfig-checker-disable-next-line
SMTP_USERNAME = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTndGcHJpUE9MNTRranUyNlRYdUYvNEcvL1ZWdU1EcldJWlVXL3FtcFU0CkdJOWhiS1hwZEg5UVRRZndiczZpWWxTQmFzR3V3VzRMRTFHZ1lxVHdZaDgKLT4gZC1ncmVhc2UKY3BDaW5ja1g1V1RiNGt1T3UrWU5qM1NEN2YveElTVGQrakl4bXUvU1J6aVFHek1QVzVoUkZYelhzNUVoCi0tLSBtZ1NLNXgwVjJ6aUFDcStURk5zN0xJOGw3dDBjbzNqM0RsbW50RngwVklVChgBoc5440LQfhGQwz3Cpi0Ms4WOMrhp79cpmA0aD6aDtWfdUW7vP4Mze+KbLBubZxBxkl3j4BiPmiM" }
# editorconfig-checker-disable-next-line
APPLE_USERNAME_1 = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdWQzaUh0UTRudzBZbG5DNzk5Uy9oMURJd1gySUY5R0ZWaTUrVmZEb0FzClkrdW8wQVdhZTFYRTkyMnNzTFNvaXM2NmdQL0V5TjJGTVZOVy9IeVFMODAKLT4gR1UxUSp2VC1ncmVhc2UKSUZVRnI1SUVJb2lSTlltRTNjM0JuNStYUVBweHV1eUF1Q0FhTi9kd3JIU0NYdWxmRlV6RXNmWQotLS0gaTFvV3F0cU1SM2wyQlpRaVliUUVwMUFBbFJyOFgxQWhOQ3REZjJBMXl4OAoiaoNJZm4wFlJVHkxDxFDoQygs+QIHL+Fv24TyoMXCrojdnB/ORAeJeyqTLAnXReXjfE2NNfEXTQ2WJFBc/uUz" }
# editorconfig-checker-disable-next-line
APPLE_USERNAME_2 = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdUNiUFVHNHJadkwrVktCKyt5WjBsbEJTK2dmREdVUXEzL0ZEOFRBa2x3CjUwc3BpanJHcDIwWlFkWkZIUHp2c1YyaUN5STFHWGdvM09PMzM1OGVVaUkKLT4gSnQ9LWdyZWFzZSBtClpYUktoSFNlNEdieU1TOG14dnNsQUdqLytLcHkzRHhzS05LMFpsZkFDQVJZUmZOTlc2NFQwSHJ4MVlSTzM0ekcKanZobGc0WG9Fekp3NFA3dnBaUDlDQ1RpSXcKLS0tIEUrSElGNWZhYkM1b01PTERZTzJ5TC9ZSlEzd3pCdHFJVm5kYnZKdzhDemsKTFpAdT/8KFWN444BQ5th1Lo6FB+kiH+roOC4QHWn6/jnpaMmVfppefLkvZqP8SQ7WUKBoA" }
# editorconfig-checker-disable-next-line
APPLE_USERNAME_3 = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZTREdVFLZUdPZDlIUmE1RzVzbUJXQkw1VDdMYWdKZ1Bsa2ZEQ1o0Z3g0CmFTMlc5VmlhWmxEMG95bjZCaWJTc1p4SjF4Nk9DNEtDSXFURno2MUFOcmsKLT4gdS1ncmVhc2UgUCVoQzNmCmVUS0hqeXE5QzRkMHZxeS9FRUo4SW9DTTU5OEc5bVFRY25oVUVYbwotLS0gcm1aSzZtMEdtUmhXLzRqUnZHWmhnNDJaR3RzRkROUE1jbnlPRTg2M2J3MAptT73ShbBITCRSvw3/dwHjImxfie/iZ7huNpz/iTKeW2qbL2hUi1AM1dYU7v54r/DFX/UsVNHI" }
# editorconfig-checker-disable-next-line
APPLE_USERNAME_4 = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSmNYWHlBdVhnV21LMkNTcFNZS0lmR3Q1UHNMYllueVpNdUpXNnU0REZBCjR2ZzMwU0xQNG05WEFkVEFkcjJ5c2Zaa0FReUMrSEdsUnlWZlE5aUllMVkKLT4gdHxibkotZ3JlYXNlCkRQNzU1aHBWL0tLVXV0ZDNBUnEwNFBBOTFRCi0tLSBwRENYNGJOZzY3VGtlekNrWCtCWVVqR2J3S0FTdHVmMmlVa1VXVllYbjVRCrofKyfCx2+kdlDao+UacHa6/5VfvmgwYhQSWgeb/giQyWJBKqtlflLm3wl041+wJ04o2g9q5ch+xHk" }
# editorconfig-checker-disable-next-line
APPLE_LIBRARY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaEYrYWJVV016RndqdjZvSFp1MmFLRVYrWCttb2I3OFFTYWMwaGtPNFJBCk9EN1pCc2tsQURGYWQwNFR1c1kxMGFXYU1NdE5rSHZxRERKdnJpbVQ3S28KLT4gfFFELWdyZWFzZSBQfCxNCmdyakFMUFVOVlNqbDB1a2pGNER1aGxqbUR0akZkS2tFU1FDZ3M1bwotLS0gQisyV1pwemV2b0YrQktITDBwYkpRWTdVZmdTWHlRaTFYcDloSkFhd0FuZwrZcrwLLV6JbFt70CbHiGhipdks3zmQOJkCzT76vj/+T62w7n9OWwxMqW/XXoq3Toenvg4RG0zHH1Zy2wKwsHVpSPS7xVedy/fiQavHx5CI" }

[tools]
age = "latest"
chezmoi = "latest"
editorconfig-checker = "latest"
gitleaks = "latest"
grype = "latest"
# lychee = "latest"
node = "latest"
# pre-commit = "latest"  # FIXME: Install pre-commit-uv instead.
prettier = "latest"
ruff = "latest"
shellcheck = "latest"
yamllint = "latest"
